import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "SnapCart | Grocery delivery in just 10 minutes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full min-h-screen bg-linear-to-b from-green-200 to-white">
        {children}
      </body>
    </html>
  );
}
